### ISSUE TITLE
Unable to get to compile on OSX 10.9 and Linux 2.6

### ISSUE THREAD

**Issue by jonberliner** [cgarciae/cybrain#5]
I've tried to installing on OSX 10.9 and Linux 2.6.18-308 and can't get to compile. Getting this error on the Linux machine:

```
running install
running build
running build_ext
cythoning cybrain.pyx to cybrain.cpp

Error compiling Cython file:
------------------------------------------------------------
...
        cdef:
            Neuron neuron
        for neuron in self.neurons:
            neuron.errorActivate()

    cpdef setData(self, double[:] data ):
                              ^
------------------------------------------------------------

cybrain.pyx:401:31: Expected an identifier or literal
building 'cybrain' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -O2 -fPIC -I/usr/local/python/lib/python2.7/site-packages/numpy/core/include -I/usr/local/python/include/python2.7 -c cybrain.cpp -o build/temp.linux-x86_64-2.7/cybrain.o
cybrain.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1
```

and this one on the Mac Machine:

```
running install
running build
running build_ext
skipping 'cybrain.cpp' Cython extension (up-to-date)
skipping 'tbrain.cpp' Cython extension (up-to-date)
running install_lib
running install_egg_info
Removing /Users/jsb/anaconda/envs/jb/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info
Writing /Users/jsb/anaconda/envs/jb/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info
```

I suspect these failures are due to having systems not included in your build folder (osx 10.6 and linux 2.7).  Do you think this is the issue/any suggestions?
